# Generated by Django 5.1.6 on 2025-02-25 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Сумма в тиынах (1 тенге = 100 тиын)')),
                ('ioka_order_id', models.CharField(help_text='ID заказа в Ioka', max_length=255, unique=True)),
                ('our_order_id', models.CharField(help_text='Наш ID заказа', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('UNPAID', 'Не оплачено'), ('PAID', 'Оплачено'), ('EXPIRED', 'Истекло')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
