"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import os

from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Загружаем .env файл
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i^zl6tox_sqq&j_oa^o*a$v0zz&29d^*=7d01wc)pp!51)y9im'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.User'
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

IOKA_API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE4MzY2NDM3NDQsImlhdCI6MTcxNjQ0ODg5MCwiYXpwIjoiZGFzaGJvYXJkIiwiaXNzIjoiZ2FybWl1cyIsInN1YiI6InVzcl9VVE5EWFoyQkhOIiwiYXVkIjpbImFjY291bnQiLCJvcmdhbml6YXRpb24iLCJnYXJtaXVzIiwidHJhbnNmZXIiLCJyZXBvcnRzIiwiY3VzdG9tZXIiLCJtYXN0ZXJwYXNzIiwicGF5b3V0cyIsImNvcmUiXSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsid2FsbGV0cy5ldmVudHM6cmVhZCIsInRyYW5zZmVyczpyZWFkIiwicmVzb3VyY2VzOnJlYWQiLCJ3aXRoZHJhd2FsczpyZWFkIiwid2FsbGV0cy53ZWJob29rczp3cml0ZSIsIndhbGxldHMud2ViaG9va3M6cmVtb3ZlIiwid2FsbGV0cy53ZWJob29rczpyZWFkIiwid2FsbGV0czp3cml0ZSIsIndhbGxldHM6cmVtb3ZlIiwid2FsbGV0czpyZWFkIiwid2FsbGV0cy53Mnc6d3JpdGUiLCJ3YWxsZXRzLncydzpyZWFkIiwid2FsbGV0cy5hY2NvdW50OnJlYWQiLCJhY2NvdW50czp3cml0ZSIsImFjY291bnRzOnJlYWQiLCJ3YWxsZXRzLnRyYW5zYWN0aW9uczp3cml0ZSIsIndhbGxldHMudHJhbnNhY3Rpb25zOnJlbW92ZSIsIndhbGxldHMudHJhbnNhY3Rpb25zOnJlYWQiLCJkZXBvc2l0czp3cml0ZSIsImRlcG9zaXRzOnJlYWQiXX0sIm9yZ2FuaXphdGlvbiI6eyJyb2xlcyI6WyJvcmdhbml6YXRpb25zOndyaXRlIiwib3JnYW5pemF0aW9uczpyZW1vdmUiLCJvcmdhbml6YXRpb25zOnJlYWQiXX0sImdhcm1pdXMiOnsicm9sZXMiOlsic2hvcHMuc3ViOndyaXRlIl19LCJ0cmFuc2ZlciI6eyJyb2xlcyI6WyJ0cmFuc2Zlci1vcmRlcnM6d3JpdGUiLCJ0cmFuc2Zlci1vcmRlcnM6cmVhZCIsImNvcnAtY2FyZHM6d3JpdGUiLCJjb3JwLWNhcmRzOnJlYWQiXX0sInJlcG9ydHMiOnsicm9sZXMiOlsicmVwb3J0czpyZWFkIiwicmVwb3J0cy5wYXlvdXRzOndyaXRlIiwicmVwb3J0cy5wYXlvdXRzOnJlYWQiXX0sImN1c3RvbWVyIjp7InJvbGVzIjpbImN1c3RvbWVyczp3cml0ZSIsImN1c3RvbWVyczpyZWFkIiwiY3VzdG9tZXJzLiouY2FyZHM6d3JpdGUiLCJjdXN0b21lcnMuKi5jYXJkczpyZWFkIl19LCJtYXN0ZXJwYXNzIjp7InJvbGVzIjpbIm1hc3RlcnBhc3Muc2Vzc2lvbnM6d3JpdGUiLCJtYXN0ZXJwYXNzLnNlc3Npb25zOnJlYWQiLCJtYXN0ZXJwYXNzLnBob25lczp3cml0ZSIsIm1hc3RlcnBhc3MuY2FyZHM6d3JpdGUiLCJtYXN0ZXJwYXNzLmNhcmRzOnJlbW92ZSIsIm1hc3RlcnBhc3MuY2FyZHM6cmVhZCJdfSwicGF5b3V0cyI6eyJyb2xlcyI6WyJyZWNlaXZlcnM6d3JpdGUiLCJyZWNlaXZlcnM6cmVhZCIsInBheW91dC1vcmRlcnM6d3JpdGUiLCJwYXlvdXQtb3JkZXJzOnJlYWQiLCJwYXlvdXQtd2ViaG9va3M6d3JpdGUiLCJwYXlvdXQtd2ViaG9va3M6cmVhZCJdfSwiY29yZSI6eyJyb2xlcyI6WyJyZWZ1bmRzOndyaXRlIiwicmVmdW5kczpyZWFkIiwiY2hlY2tzOndyaXRlIiwiY2hlY2tzOnJlYWQiLCJzcGxpdHM6d3JpdGUiLCJzcGxpdHM6cmVhZCIsInBheW1lbnQtbGlua3M6Y3JlYXRlIiwicGF5bWVudC1saW5rczpyZWFkIiwicGF5bWVudHM6cmVhZCIsImFuYWx5dGljczpyZWFkIiwib3JkZXJzOmNhbmNlbCIsIm9yZGVyczpjcmVhdGUiLCJvcmRlcnM6cmVmdW5kIiwib3JkZXJzOmNhcHR1cmUiLCJvcmRlcnM6cmVhZCIsInN1YnNjcmlwdGlvbnM6d3JpdGUiLCJzdWJzY3JpcHRpb25zOnJlYWQiLCJ3ZWJob29rczp3cml0ZSIsIndlYmhvb2tzOnJlYWQiXX19LCJ1c2VyIjp7ImlkIjoidXNyX1VUTkRYWjJCSE4iLCJkaXNwbGF5X25hbWUiOiJBbGliZWsgLSIsInVzZXJuYW1lIjoiYWxpYmVrYmFrZGF1bGV0QGdtYWlsLmNvbSIsImZpcnN0X25hbWUiOiJBbGliZWsiLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJsYXN0X25hbWUiOiItIiwiZW1haWwiOiJhbGliZWtiYWtkYXVsZXRAZ21haWwuY29tIiwic3RhdHVzIjoiQUNUSVZFIn0sInNob3AiOnsiaWQiOiJzaHBfUEtFS1pKVVZIRiIsIm93bmVyX2lkIjoidXNyX1VUTkRYWjJCSE4iLCJpc19kZWFsZXIiOmZhbHNlLCJiaW4iOiIxMTExMTExMTExMTEiLCJkaXNwbGF5X25hbWUiOiJCb3N0b24gU2Nob29sIiwic3RhdHVzIjoiQUNDRVBURUQiLCJzdWIiOltdfSwibG9jYWxlIjoicnUifQ.ED57l82g1R7GNsQQ4YPJOcUzadp_vO6KrFrmWvUaGO1FEjF9NSm1uxdAAt4qnjx-GYSm5GJBaPGmb5lO7dp20XwkCk5JUYZQHFl6iaADtgvhlN1Smf5nzo4WqxCntjbbx1j8BVJPlzkpagiDBjXQjv9Wj0jY4tiOj5E81tTZS5xWLnO-ZAZV0emP5wplB2k9FpKFsylGOduQLNMDWTRNK9nwIZq3GGnGWA1y8-3MT-RPWtXZ1hXWUzWjQR2YKE5bpwy3RLXtkWOHwQGgUz89FwOKysHMsTvjaTEGHPyM57yoHU5tcsHEPZUcq5_MEXP0obcm4K1ihME7nhY3azmNKg"
IOKA_API_URL = "https://stage-api.ioka.kz/v2/orders"  # Для тестирования, поменяй для продакшена

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'chatbot',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', ''),  # по умолчанию пусто, можешь указать '5432'
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/uploads/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
